name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.organization.name}
website: ${project.organization.url}

main: ${mainClass}
depend: [Spout]
load: POSTWORLD

permissions:
    recipes.*:
        description: Gives access to all recipes abilities
        children:
            reserve.admin: true
            reserve.view: true
    recipes.admin:
        description:
        default: op
    recipes.use:
        description:
        default: true
    recipes.view:
        description:
        default: op